global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: elitemini
    static_configs:
      - targets: ['100.80.59.3:9100']
        labels:
          instance: 100.80.59.3:9100
